# Clustering Analysis

In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Alec","Alec","Ben","Charlie","Charlie"],
    "Course":["Math","Bio","Math","Math","Chem"],
    "Grade":["A","B","C","B","C"]
})
df

      Name Course Grade
0     Alec   Math     A
1     Alec    Bio     B
2      Ben   Math     C
3  Charlie   Math     B
4  Charlie   Chem     C

## Preprocessing

### One-hot encoding
Convert categorical to binary data

In [2]:
# Method 1: Use pandas get_dummies

pd.get_dummies(df, columns=["Course"], dtype=float)

      Name Grade  Course_Bio  Course_Chem  Course_Math
0     Alec     A         0.0          0.0          1.0
1     Alec     B         1.0          0.0          0.0
2      Ben     C         0.0          0.0          1.0
3  Charlie     B         0.0          0.0          1.0
4  Charlie     C         0.0          1.0          0.0

In [3]:
# Method 2: Use sklearn OneHotEncoder
# This method help to keep both original and encoded columns
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[["Course"]])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["Course"]))

pd.concat([df, encoded_df], axis=1)

      Name Course Grade  Course_Bio  Course_Chem  Course_Math
0     Alec   Math     A         0.0          0.0          1.0
1     Alec    Bio     B         1.0          0.0          0.0
2      Ben   Math     C         0.0          0.0          1.0
3  Charlie   Math     B         0.0          0.0          1.0
4  Charlie   Chem     C         0.0          1.0          0.0

### Ordinal encoding

Convert descriptive variable to ordinal variable

In [4]:
# Method 1: Apply mapping manually
dfc = df.copy()

grade_encoded_map = {"A": 1, "B": 2, "C": 3}

dfc["Grade_encoded"] = dfc["Grade"].map(grade_encoded_map)

dfc

      Name Course Grade  Grade_encoded
0     Alec   Math     A              1
1     Alec    Bio     B              2
2      Ben   Math     C              3
3  Charlie   Math     B              2
4  Charlie   Chem     C              3

In [5]:
# Method 2: Use sklearn OrdinalEncoder
from sklearn.preprocessing import OrdinalEncoder

ord_encoder = OrdinalEncoder(categories=[["A","B","C"]]) # Make sure it's double squared

dfc["Grade_encoded_2"] = ord_encoder.fit_transform(dfc[["Grade"]]) # Make sure it's double squared

dfc

      Name Course Grade  Grade_encoded  Grade_encoded_2
0     Alec   Math     A              1              0.0
1     Alec    Bio     B              2              1.0
2      Ben   Math     C              3              2.0
3  Charlie   Math     B              2              1.0
4  Charlie   Chem     C              3              2.0

## Scale/Standardize

Apply feature scaling using sklearn's MinMaxScaler or StandardScaler

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Choose one of them
# StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

## K-means 

### Find optimal K